

compiler:
  solc:
    remappings:
      - '@CCIP=..\..\CCIP_modules'
      - '@CHAINLINK=..\..\CHAINLINK_modules'
dotenv: .env

networks:
  sepolia:
    # see https://docs.chain.link/ccip/supported-networks
    link     : "0x779877A7B0D9E8603169DdbD7836e478b4624789"
    BnM      : "0xFd57b4ddBf88a4e07fF4e34C487b99af2Fe82a05"
    LnM      : "0x466D489b6d36E7E3b824ef491C225F5830E81cC1"
    router   : "0xD0daae2231E9CB96b94C8512223533293C3693Bf"
    # my deployments
    lendable  : ""


  polygon-test:
    # see https://docs.chain.link/ccip/supported-networks
    link       : "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"
    BnM        : "0xf1E3A5842EeEF51F2967b3F05D45DD4f4205FF40"
    LnM        : "0xc1c76a8c5bFDE1Be034bbcD930c668726E7C1987"
    router     : "0x70499c328e1E2a3c41108bd3730F6670a44595D1"
    # my deployments
    lendable : ""


wallets:
  GOOG_key  : ${PRIVATE_KEY_GOOGLE}
  EXPLOR_key: ${PRIVATE_KEY_EXPLORER}
