compiler:
  solc:
    version: 0.7.6
    remappings:
      - '@uniswap=node_modules\@uniswap'
      - '@openzeppelin=node_modules\@openzeppelin'
dotenv: .env
networks:

  # ========== UNISWAP TESTNETS ==========
    polygon-amoy:

      #---- MOCK ERC20s
      # from: https://polygonscan.com/tokens
      weth : "0x6863b3e4f6078105A02421FEFAa756E6fBb418cA"
      sand : "0x84362d16D098c509e77029E0D4A6175B1A483b3e"
      link : "0xf4447503eb3a9E9574627B01D38956C140fd42dC"

      # uniswap mocks
      Factory         : "0x72d7F6F943C40C1E2dB3E69A7C55eE4Ee2a53196"
      LiquidityMiner  : ""

      #---------- TESTING
      MyMath : "0x93b75f9e1c9A53751b10a0cf0d144C55CdeBbfCa"

    sepolia:

      #---- MOCK ERC20s
      # from: https://polygonscan.com/tokens
      weth : ""
      sand : ""
      link : ""

      # uniswap mocks
      Factory : "0x0227628f3F023bb0B980b67D528571c95c6DaC1c"
      NonfungiblePositionManager : "0x1238536071E1c677A632429e3655c799b22cDA52"

      #---------- TESTING
      MyMath : ""

    arbitrum-sepolia:

      #---- MOCK ERC20s
      # from: https://polygonscan.com/tokens
      weth : "0xaa8138d6295d127085B60021718e20Fac918C65d"
      link : "0x44578CbA77E0372587486DA93Df337Cba0bbD4d0"

      # uniswap mocks
      Factory : "0x248AB79Bbb9bC29bB72f7Cd42F17e054Fc40188e"
      NonfungiblePositionManager : "0x6b2937Bde17889EDCf8fbD8dE31C3C2a70Bc4d65"

      #---------- TESTING
      MyMath : "0x478fcf69f121C3054525D6403d1BB5c62cac6563"
      LiquidityMiner: "0x1a7FCB83B4F0C18A147FDb020F843FF84B6AB333"


    # ========== UNISWAP MAINNETS ==========

    # +
    # Alchemy: [need to upgrade]
    # chain: 43114
    # avax deploy cost: 0.13310886600000002 ETH (338.42929180500005 USD)
    avax-main:
      Factory : "0x740b1c1de25031C31FF4fC9A62f554A55cdC1baD"
      NonfungiblePositionManager : "0x655C406EBFa14EE2006250925e54ec43AD184f8B"


    # +
    # Alchemy: https://arb-mainnet.g.alchemy.com/v2/OeVRTKqUBtFwUKVXZnZC8z7Wjwvftb71
    # chain: 42161
    # arbitrum deploy cost  :: 0.07895948814 ETH (200.75449859595003 USD)
    arbitrum-main:
      # uniswap mocks
      Factory : "0x1F98431c8aD98523631AE4a59f267346ea31F984"
      NonfungiblePositionManager : "0xC36442b4a4522E871399CD717aBDD847Ab11FE88"

    # -
    # Alchemy: [need to upgrade]
    # chain: 56
    # deploy cost: ~$
    bnb-main:
      Factory : "0xdB1d10011AD0Ff90774D0C6Bb92e5C5c8b4461F7"
      NonfungiblePositionManager : "0x7b8A01B39D58278b5DE7e48c8449c9f4F5170613"

    # +
    # Alchemy: https://base-mainnet.g.alchemy.com/v2/OeVRTKqUBtFwUKVXZnZC8z7Wjwvftb71
    # chain: 8453
    # base deploy cost  :: 0.03231005931151325 ETH (82.14832579952242 USD)
    base-main:
      Factory : "0x33128a8fC17869897dcE68Ed026d694621f6FDfD"
      NonfungiblePositionManager : "0x03a520b32C04BF3bEEf7BEb72E919cf822Ed34f1"

    # -
    # Alchemy: https://blast-mainnet.g.alchemy.com/v2/OeVRTKqUBtFwUKVXZnZC8z7Wjwvftb71
    # chain: 81457
    # blast deploy cost  :: 0.03201627472754348 ETH (81.4013784947793 USD)
    blast-main:
      Factory : "0x792edAdE80af5fC680d96a2eD80A44247D2Cf6Fd"
      NonfungiblePositionManager : "0xB218e4f7cF0533d4696fDfC419A0023D33345F28"

    # -
    # Alchemy: NA
    # chain: 42220
    # deploy cost: ~$
    celo-main:
      Factory : "0xAfE208a311B21f13EF87E33A90049fC17A7acDEc"
      NonfungiblePositionManager : "0x3d79EdAaBC0EaB6F08ED885C05Fc0B014290D95A"    

    # -
    # Alchemy: https://eth-mainnet.g.alchemy.com/v2/OeVRTKqUBtFwUKVXZnZC8z7Wjwvftb71
    # chain: 10001
    # ethereum deploy cost  :: 0.09663999104888313 ETH (245.70717724178536 USD)
    ethereum-main:
      Factory : "0x1F98431c8aD98523631AE4a59f267346ea31F984"
      NonfungiblePositionManager : "0xC36442b4a4522E871399CD717aBDD847Ab11FE88"    

    # - ??? Optimistic Ethereum
    # Alchemy: https://opt-mainnet.g.alchemy.com/v2/OeVRTKqUBtFwUKVXZnZC8z7Wjwvftb71
    # chain: 10
    # ...UNAUTHORIZED???
    optimism-main:
      Factory : "0x1F98431c8aD98523631AE4a59f267346ea31F984"
      NonfungiblePositionManager : "0xC36442b4a4522E871399CD717aBDD847Ab11FE88"   

    # +
    # Alchemy: https://polygon-mainnet.g.alchemy.com/v2/OeVRTKqUBtFwUKVXZnZC8z7Wjwvftb71
    # chain: 137
    # polygon deploy cost  :: 0.04637307525166096 ETH (117.903543827348 USD)
    polygon-main:
      Factory : "0x1F98431c8aD98523631AE4a59f267346ea31F984"
      NonfungiblePositionManager : "0xC36442b4a4522E871399CD717aBDD847Ab11FE88"   

    # Alchemy: https://worldchain-mainnet.g.alchemy.com/v2/OeVRTKqUBtFwUKVXZnZC8z7Wjwvftb71
    # chain: 480
    # worldchain deploy cost  :: 0.03227837226120664 ETH (82.06776147411789 USD)
    worldchain:
      Factory : "0x7a5028BDa40e7B173C278C5342087826455ea25a"
      NonfungiblePositionManager : "0xec12a9F9a09f50550686363766Cc153D03c27b5e"  

    # - ?? zkEVM
    # Alchemy: https://zksync-mainnet.g.alchemy.com/v2/OeVRTKqUBtFwUKVXZnZC8z7Wjwvftb71
    # chain: 324
    # !!error!!: Failed to serialize transaction: toAddressIsNull
    zksync:
      Factory : "0x8FdA5a7a8dCA67BBcDd10F02Fa0649A937215422"
      NonfungiblePositionManager : "0x0616e5762c1E7Dc3723c50663dF10a162D690a86"  

    # Alchemy: https://zora-mainnet.g.alchemy.com/v2/OeVRTKqUBtFwUKVXZnZC8z7Wjwvftb71
    # chain: 7777777
    # zora deploy cost  :: 0.0323788199029304 ETH (82.32314960320053 USD)
    zora:
      Factory : "0x7145F8aeef1f6510E92164038E1B6F8cB2c42Cbb"
      NonfungiblePositionManager : "0xbC91e8DfA3fF18De43853372A3d7dfe585137D78"  


wallets:
  GOOG_key  : ${PRIVATE_KEY_GOOGLE}
  EXPLOR_key: ${PRIVATE_KEY_EXPLORER}
