dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.3
  - smartcontractkit/chainlink-brownie-contracts@0.6.1

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:

  polygon-test:
    link_token: "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"

    matic_to_usd  : '0xd0D5e3DB44DE05E9F294BB0a3bEEaF030DE24Ada'
    eth_to_usd    : '0x0715A7794a1dc8e42615F059dD6e406A6594651A'
    link_to_matic : '0x12162c3E810393dEC01362aBf156D7ecf6159528'
    link_to_usd   : '0x1C2252aeeD50e0c9B64bDfF2735Ee3C932F5C408'

    nft_ : ""
  
